image: python:3.7
stages:
  - validate
  - release

Run Unit Tests:
  stage: validate
  script:
    - python3 -m pip install -U pipenv
    - pipenv install --dev --ignore-pipfile
    - bin/verify.sh

Release appian-locust to Pypi:
  rules:
    - if: '$CI_COMMIT_TAG != null && $CI_PROJECT_NAMESPACE =~ /^appian-oss.*/ && $CI_COMMIT_REF_NAME == "master"'
  stage: release
  before_script:
    - bin/writeTagToVersionFile.sh
  script:
    - echo "Publishing appian-locust Python Package to Pypi"
    - bin/releaseLib.sh
